// src/views/sales/salesConfig.js

export const SALES_UI = {
  header: {
    backText: 'Back to Master Catalog',
    title: 'Point of Sale & Stock Out',
    subtitle: 'Disburse inventory, stage bulk items, apply loyalty agreements, and issue verified receipts',
    badgeSuffix: 'Orders Processed',
  },
  form: {
    title: 'Order Dispatch',
    stepBuilder: 'Step 1 of 2 · Build Order',
    stepConfirm: 'Step 2 of 2 · Confirm Sale',
    branchLabel: 'Branch Source',
    stockLabel: 'Available On-Hand',
    variantLabel: 'Sub-Product / Variant',
    qtyLabel: 'Quantity to Add',
    addItemBtn: 'Add to Order',
    dividerText: 'Buyer Agreement & Loyalty',
    modes: {
      existing: 'Saved Profile',
      new: '+ New Client',
    },
    newCustomerPlaceholder: 'Enter client or boba shop business name',
    buyerDiscountLabel: 'Contract Discount (%)',
    updateProfileLabel: (discount) => `Update permanent default rate to ${discount}%`,
    specialDiscountLabel: 'Occasion / Clearance (%)',
    reasonLabel: 'Clearance or Occasion Reason',
    reasonPlaceholder: 'e.g. Near-Expiry Clearance, Promo Event, Damaged Box',
    proceedButton: 'Proceed to Confirmation',
    backToCartButton: 'Back to Edit Items',
    confirmSaleButton: 'Authorize & Complete Sale',
  },
  cart: {
    title: 'Staged Order Items',
    emptyTitle: 'No items staged yet',
    emptySub: 'Choose a product SKU and quantity above, then click Add to Order.',
    clearCart: 'Clear Order',
    itemsCount: (count, units) => `${count} ${count === 1 ? 'item' : 'items'} (${units} units)`,
  },
  confirmation: {
    title: 'Order Confirmation & Verification',
    subtitle: 'Verify staged quantities, fulfillment branch, pricing, and applied buyer discounts before final deduction.',
    branchHeader: 'Fulfillment Branch',
    buyerHeader: 'Buyer Profile',
    discountBreakdown: 'Discounts Applied',
    stagedProducts: 'Order Line Items',
    warningNotice: 'Confirmation will immediately deduct inventory quantities across all selected SKUs from this branch.',
  },
  summary: {
    subtotal: 'Order Subtotal',
    discount: (pct) => `Total Discount (${pct}%)`,
    finalPayable: 'Final Payable',
  },
  ledger: {
    title: 'Completed Receipts',
    loggedSuffix: 'logged',
    emptyTitle: 'No transactions recorded',
    emptySub: 'Completed sales processed this session will stream here live.',
  },
}
